/* Header for module mt10750 generated by GPM 1/5/2000 */
#ifndef MT10750_P_H
#define MT10750_P_H
/*
        * This module contains all of the "assembly" routines. To add an
        * assembly routine:
        *
        * 1. Add a new opcode
        * -files opcodes.p opcodes.x
        *
        * 2. Add the assembly routine
        *-files vth.p vth.x
        *
        * 3. Add a new trace routine
        * -files trc/src/trc.p trc/src/trc.x
        *
        * 4. Add the new parse routine to panel
        *-files panel/src/parse.p panel/src/parse.x panel/src/panel.p
        *
*/

/*
        * To add a new opcode
        * 1. Add the new opcode_LEX to parse.x
        * 2. Increment MAX_COMMAND in the procedure parse_command
        * 3. Add new opcode to the parse table
        * 4. Add the new parse routine and its external
        * 5. Add call to parse routine in panel.p
*/
#include "../../../u/src/hdw_p.h"
#include "../../../dgn/src/dgnconfig_p.h"
#include "../../../dgn/src/termio_p.h"
#include "../../../dgn/src/testdec_p.h"
#include "../../../dgn/src/execsup_p.h"
#include "../../../vth/src/capasm_p.h"
#include "../../../vth/src/macasm_p.h"
#include "../../../vth/src/aimasm_p.h"
#include "../../../vth/src/pinasm_p.h"
#include "../../../vth/src/result_p.h"
#include "../../../dgn/src/strdec.h"
#include "../../../vth/src/vth_p.h"
#include "../../../vth/src/vthsup_p.h"
#include "../../../vth/src/standard_p.h"
#include "../../../vth/src/strings_p.h"
#include "../../../uCC/src/future.h"
#include "mt9000_p.h"
#include "mtglobal_p.h"


void t10800(int mod_id, int slot);
void t10802(int mod_id, int slot);
void t10804(int mod_id, int slot);
void t10806(int mod_id, int slot);
void t10820(int mod_id, int slot);
void t10821(int mod_id, int slot);
void t10823(int mod_id, int slot);
void t10829(int mod_id, int slot);
void t10830(int mod_id, int slot);
void t10832(int mod_id, int slot);
void t10835(int mod_id, int slot);
void t10836(int mod_id, int slot);
void t10840(int mod_id, int slot);
void t10841(int mod_id, int slot);
void t10847(int mod_id, int slot);
void t10848(int mod_id, int slot);
void t10850(int mod_id, int slot);
void t10851(int mod_id, int slot);
void t10852(int mod_id, int slot);
void t10853(int mod_id, int slot);
void t10860(int mod_id, int slot);
void t10861(int mod_id, int slot);
void t10862(int mod_id, int slot);
void t10870(int mod_id, int slot);
void t10871(int mod_id, int slot);
void t10872(int mod_id, int slot);
void t10873(int mod_id, int slot);
void t10882(int mod_id, int slot);
void t10883(int mod_id, int slot);
void t10900(int mod_id, int slot);
void t10901(int mod_id, int slot);
void t10907(int mod_id, int slot);
void t10909(int mod_id, int slot);
void t10910(int mod_id, int slot);
void t10911(int mod_id, int slot);
void t10917(int mod_id, int slot);
void t10918(int mod_id, int slot);
void t10919(int mod_id, int slot);
void t10920(int mod_id, int slot);
void t10921(int mod_id, int slot);
void t10930(int mod_id, int slot);
void t10999(int mod_id, int slot);

#endif
