/* Header for module mt9250, generated by p2c */
#ifndef MT9250_P_H
#define MT9250_P_H

#define NUM_UTIL_SID 27
#define MSG_SIZE 255

/*
        * This module contains all of the "assembly" routines. To add an
        * assembly routine:
        *
        * 1. Add a new opcode
        * -files opcodes.p opcodes.x
        *
        * 2. Add the assembly routine
        *-files vth.p vth.x
        *
        * 3. Add a new trace routine
        * -files trc/src/trc.p trc/src/trc.x
        *
        * 4. Add the new parse routine to panel
        *-files panel/src/parse.p panel/src/parse.x panel/src/panel.p
        *
*/

/*
        * To add a new opcode
        * 1. Add the new opcode_LEX to parse.x
        * 2. Increment MAX_COMMAND in the procedure parse_command
        * 3. Add new opcode to the parse table
        * 4. Add the new parse routine and its external
        * 5. Add call to parse routine in panel.p
*/
#include "../../../u/src/hdw_p.h"
#include "../../../dgn/src/dgnconfig_p.h"
#include "../../../dgn/src/termio_p.h"
#include "../../../dgn/src/testdec_p.h"
#include "../../../dgn/src/execsup_p.h"
#include "../../../vth/src/capasm_p.h"
#include "../../../vth/src/macasm_p.h"
#include "../../../vth/src/aimasm_p.h"
#include "../../../vth/src/pinasm_p.h"
#include "../../../vth/src/result_p.h"
#include "../../../dgn/src/strdec.h"
#include "../../../vth/src/vth_p.h"
#include "../../../vth/src/vthsup_p.h"
#include "../../../vth/src/standard_p.h"
#include "../../../vth/src/strings_p.h"
#include "../../../dgn/src/limits_p.h"
#include "../../../dgn/src/convert.h"
#include "mtglobal_p.h"

void t9250(int mod_id, int slot);
void t9252(int mod_id, int slot);
void t9255(int mod_id, int slot);
void t9256(int mod_id, int slot);
void t9260(int mod_id, int slot);
void t9265(int mod_id, int slot);
void t9266(int mod_id, int slot);
void t9267(int mod_id, int slot);
void t9268(int mod_id, int slot);
void t9270(int mod_id, int slot);
void t9274(int mod_id, int slot);
void t9275(int mod_id, int slot);
void t9276(int mod_id, int slot);
void t9277(int mod_id, int slot);
void t9300(int mod_id, int slot);
void t9301(int mod_id, int slot);
void t9305(int mod_id, int slot);
void t9306(int mod_id, int slot);
void t9310(int mod_id, int slot);
void t9315(int mod_id, int slot);
void t9316(int mod_id, int slot);
void t9317(int mod_id, int slot);
void t9318(int mod_id, int slot);
void t9320(int mod_id, int slot);
void t9324(int mod_id, int slot);
void t9325(int mod_id, int slot);
void t9326(int mod_id, int slot);
void t9327(int mod_id, int slot);
void t9355(int mod_id, int slot);
void t9360(int mod_id, int slot);
void t9365(int mod_id, int slot);
void t9366(int mod_id, int slot);
void t9367(int mod_id, int slot);
void t9370(int mod_id, int slot);
void t9371(int mod_id, int slot);
void t9372(int mod_id, int slot);
void t9380(int mod_id, int slot);
void t9383(int mod_id, int slot);
void t9385(int mod_id, int slot);
void t9386(int mod_id, int slot);
void t9387(int mod_id, int slot);
void t9390(int mod_id, int slot);
void t9391(int mod_id, int slot);
void t9392(int mod_id, int slot);
void t9393(int mod_id, int slot);
void t9394(int mod_id, int slot);
void t9410(int mod_id, int slot);
void t9415(int mod_id, int slot);
void t9416(int mod_id, int slot);
void t9420(int mod_id, int slot);
void t9421(int mod_id, int slot);
void t9425(int mod_id, int slot);
void t9426(int mod_id, int slot);
void t9427(int mod_id, int slot);
void t9428(int mod_id, int slot);
void t9440(int mod_id, int slot);
void t9450(int mod_id, int slot);
void t9451(int mod_id, int slot);
int t9430(int mod_id);
void t9431(int mod_id, int slot);
void t9452(int mod_id, int slot);
void t9453(int mod_id, int slot);
void t9454(int mod_id, int slot);
void t9455(int mod_id, int slot);
void t9456(int mod_id, int slot);
void t9457(int mod_id, int slot);
void t9458(int mod_id, int slot);
void t9459(int mod_id, int slot);
void t9460(int mod_id, int slot);
void t9461(int mod_id, int slot);
void t9462(int mod_id, int slot);
void t9463(int mod_id, int slot);
void t9465(int mod_id, int slot);
void t9466(int mod_id, int slot);
void t9470(int mod_id, int slot);
void t9471(int mod_id, int slot);
void t9472(int mod_id, int slot);
void t9474(int mod_id, int slot);
void t9475(int mod_id, int slot);
void t9476(int mod_id, int slot);
void t9477(int mod_id, int slot);
void t9480(int mod_id, int slot);
void t9481(int mod_id, int slot);
void t9482(int mod_id, int slot);
void t9461(int mod_id, int slot);
void t9462(int mod_id, int slot);
void t9463(int mod_id, int slot);

void t9441(int mod_id, int slot);
void t9442(int mod_id, int slot);
void t9443(int mod_id, int slot);
void t9444(int mod_id, int slot);
void t9445(int mod_id, int slot);
void t9446(int mod_id, int slot);
void t9447(int mod_id, int slot);
void t9448(int mod_id, int slot);
void t9449(int mod_id, int slot);


#endif
