/* Header for module mt9750, generated by p2c */
#ifndef MT9750_P_H
#define MT9750_P_H
/*
        * This module contains all of the "assembly" routines. To add an
        * assembly routine:
        *
        * 1. Add a new opcode
        * -files opcodes.p opcodes.x
        *
        * 2. Add the assembly routine
        *-files vth.p vth.x
        *
        * 3. Add a new trace routine
        * -files trc/src/trc.p trc/src/trc.x
        *
        * 4. Add the new parse routine to panel
        *-files panel/src/parse.p panel/src/parse.x panel/src/panel.p
        *
*/

/*
        * To add a new opcode
        * 1. Add the new opcode_LEX to parse.x
        * 2. Increment MAX_COMMAND in the procedure parse_command
        * 3. Add new opcode to the parse table
        * 4. Add the new parse routine and its external
        * 5. Add call to parse routine in panel.p
*/
#include "../../../u/src/hdw_p.h"
#include "../../../dgn/src/dgnconfig_p.h"
#include "../../../dgn/src/termio_p.h"
#include "../../../dgn/src/testdec_p.h"
#include "../../../dgn/src/execsup_p.h"
#include "../../../vth/src/capasm_p.h"
#include "../../../vth/src/macasm_p.h"
#include "../../../vth/src/aimasm_p.h"
#include "../../../vth/src/pinasm_p.h"
#include "../../../vth/src/result_p.h"
#include "../../../dgn/src/strdec.h"
#include "../../../vth/src/vth_p.h"
#include "../../../vth/src/vthsup_p.h"
#include "../../../vth/src/standard_p.h"
#include "../../../vth/src/strings_p.h"
#include "mt9000_p.h"
#include "mtglobal_p.h"

void t9800(int mod_id, int slot);
void t9801(int mod_id, int slot);
void t9802(int mod_id, int slot);
void t9803(int mod_id, int slot);
void t9804(int mod_id, int slot);
void t9805(int mod_id, int slot);
void t9806(int mod_id, int slot);
void t9807(int mod_id, int slot);
void t9811(int mod_id, int slot);
void t9820(int mod_id, int slot);
void t9821(int mod_id, int slot);
void t9823(int mod_id, int slot);
void t9828(int mod_id, int slot);
void t9829(int mod_id, int slot);
void t9830(int mod_id, int slot);
void t9832(int mod_id, int slot);
void t9835(int mod_id, int slot);
void t9836(int mod_id, int slot);
void t9837(int mod_id, int slot);
void t9840(int mod_id, int slot);
void t9841(int mod_id, int slot);
void t9844(int mod_id, int slot);
void t9847(int mod_id, int slot);
void t9848(int mod_id, int slot);
void t9849(int mod_id, int slot);
void t9850(int mod_id, int slot);
void t9851(int mod_id, int slot);
void t9852(int mod_id, int slot);
void t9853(int mod_id, int slot);
void t9859(int mod_id, int slot);
void t9860(int mod_id, int slot);
void t9861(int mod_id, int slot);
void t9862(int mod_id, int slot);
void t9870(int mod_id, int slot);
void t9871(int mod_id, int slot);
void t9882(int mod_id, int slot);
void t9883(int mod_id, int slot);
void t9900(int mod_id, int slot);
void t9901(int mod_id, int slot);
void t9905(int mod_id, int slot);
void t9906(int mod_id, int slot);
void t9907(int mod_id, int slot);
void t9909(int mod_id, int slot);
void t9910(int mod_id, int slot);
void t9911(int mod_id, int slot);
void t9917(int mod_id, int slot);
void t9920(int mod_id, int slot);
void t9921(int mod_id, int slot);
void t9930(int mod_id, int slot);
void t9995(int mod_id, int slot);
void t9997(int mod_id, int slot);
void t9998(int mod_id, int slot);
void t9999(int mod_id, int slot);

#endif
