init_digital();
set_fclks_per_vector_pair(4);
set_driver_range(0.2, 3.5);
set_slew_rate(225);
set_receiver_range(1.5, 1.5);
set_chan_drv(mod_id, slot, 0, 2, 0, 4, 0, ONE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 1, 2, 0, 4, 0, ONE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 2, 2, 0, 4, 0, ONE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 3, 2, 0, 4, 0, ONE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 4, 2, 0, 4, 0, ONE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 5, 2, 0, 4, 0, ONE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 6, 2, 0, 4, 0, ONE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 7, 2, 0, 4, 0, ONE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
start_vector(0, 2, 256, 256);
end_vector();
start_vector(1, 2, 0, 1);
end_vector();
start_vector(16, 2, 0, 1);
set_driver(mod_id, slot, 0, 0, ZERO_NUM);
set_driver(mod_id, slot, 1, 0, ZERO_NUM);
set_driver(mod_id, slot, 2, 0, ZERO_NUM);
set_driver(mod_id, slot, 3, 0, ZERO_NUM);
set_driver(mod_id, slot, 4, 0, ZERO_NUM);
set_driver(mod_id, slot, 5, 0, ZERO_NUM);
set_driver(mod_id, slot, 6, 0, ZERO_NUM);
set_driver(mod_id, slot, 7, 0, ZERO_NUM);
farm_tic(mod_id);
end_vector();
start_vector(17, 2, 0, 1);
set_driver(mod_id, slot, 0, 0, ONE_NUM);
set_driver(mod_id, slot, 1, 0, ONE_NUM);
set_driver(mod_id, slot, 2, 0, ONE_NUM);
set_driver(mod_id, slot, 3, 0, ONE_NUM);
set_driver(mod_id, slot, 4, 0, ONE_NUM);
set_driver(mod_id, slot, 5, 0, ONE_NUM);
set_driver(mod_id, slot, 6, 0, ONE_NUM);
set_driver(mod_id, slot, 7, 0, ONE_NUM);
farm_tic(mod_id);
end_vector();
start_vector(18, 2, 0, 1);
set_driver(mod_id, slot, 0, 0, ZERO_NUM);
set_driver(mod_id, slot, 1, 0, ZERO_NUM);
set_driver(mod_id, slot, 2, 0, ZERO_NUM);
set_driver(mod_id, slot, 3, 0, ZERO_NUM);
set_driver(mod_id, slot, 4, 0, ZERO_NUM);
set_driver(mod_id, slot, 5, 0, ZERO_NUM);
set_driver(mod_id, slot, 6, 0, ZERO_NUM);
set_driver(mod_id, slot, 7, 0, ZERO_NUM);
end_vector();
start_vector(19, 2, 0, 1);
set_driver(mod_id, slot, 0, 0, ONE_NUM);
set_driver(mod_id, slot, 1, 0, ONE_NUM);
set_driver(mod_id, slot, 2, 0, ONE_NUM);
set_driver(mod_id, slot, 3, 0, ONE_NUM);
set_driver(mod_id, slot, 4, 0, ONE_NUM);
set_driver(mod_id, slot, 5, 0, ONE_NUM);
set_driver(mod_id, slot, 6, 0, ONE_NUM);
set_driver(mod_id, slot, 7, 0, ONE_NUM);
end_vector();
add_seq_loc(0, 1, SEQ_NO_FLAG);
add_seq_loc(1, 1, SEQ_NO_FLAG);
add_seq_loc(2, 1, SEQ_NO_FLAG);
add_seq_loc(3, 1, SEQ_NO_FLAG);
add_seq_loc(4, 1, SEQ_NO_FLAG);
add_seq_loc(5, 1, SEQ_NO_FLAG);
add_seq_loc(6, 1, SEQ_NO_FLAG);
add_seq_loc(7, 1, SEQ_NO_FLAG);
add_seq_loc(8, 1, SEQ_NO_FLAG);
add_seq_loc(9, 1, SEQ_NO_FLAG);
add_seq_loc(10, 1, SEQ_NO_FLAG);
add_seq_loc(11, 1, SEQ_NO_FLAG);
add_seq_loc(12, 1, SEQ_NO_FLAG);
add_seq_loc(13, 1, SEQ_NO_FLAG);
add_seq_loc(14, 1, SEQ_NO_FLAG);
add_seq_loc(15, 1, SEQ_NO_FLAG);
add_seq_loc(16, 16, SEQ_NO_FLAG);
add_seq_loc(17, 17, SEQ_NO_FLAG);
add_seq_loc(18, 18, SEQ_NO_FLAG);
add_seq_loc(19, 19, SEQ_NO_FLAG);
add_vect_cmd(0, 0, PROG_NOP_FLAG);
add_vect_cmd(1, 0, PROG_NOP_FLAG);
add_vect_cmd(2, 0, PROG_NOP_FLAG);
add_jmp_cmd(3, 0, 256, PROG_NOP_FLAG);
add_jmpq_cmd(256, 17, CPU_NUM, 258, PROG_FE_FLAG);
add_jmp_cmd(257, 18, 256, PROG_FE_FLAG);
add_jmpq_cmd(258, 17, CPU_BAR_NUM, 512, PROG_FE_FLAG);
add_jmp_cmd(259, 18, 258, PROG_FE_FLAG);
add_jmpq_cmd(512, 16, CPU_NUM, 514, PROG_FE_FLAG);
add_jmp_cmd(513, 19, 512, PROG_FE_FLAG);
add_jmpq_cmd(514, 16, CPU_BAR_NUM, 256, PROG_FE_FLAG);
add_jmp_cmd(515, 19, 514, PROG_FE_FLAG);
add_sls_cmd(516, 0, 13, PROG_NOP_FLAG);
add_vect_cmd(517, 0, PROG_NOP_FLAG+PROG_HALT_FLAG);
add_vect_cmd(518, 0, PROG_NOP_FLAG);
add_vect_cmd(519, 0, PROG_NOP_FLAG);
end_digital();
