init_digital();
set_fclks_per_vector_pair(2);
set_chan_drv(mod_id, slot, 0, 1, 0, 2, 0, TOGGLE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 1, 1, 0, 2, 0, TOGGLE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 2, 1, 0, 2, 0, TOGGLE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 3, 1, 0, 2, 0, TOGGLE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 4, 1, 0, 2, 0, TOGGLE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 5, 1, 0, 2, 0, TOGGLE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 6, 1, 0, 2, 0, TOGGLE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 7, 1, 0, 2, 0, TOGGLE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 8, 1, 0, 2, 0, TOGGLE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 9, 1, 0, 2, 0, TOGGLE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 10, 1, 0, 2, 0, TOGGLE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 11, 1, 0, 2, 0, TOGGLE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 12, 1, 0, 2, 0, TOGGLE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 13, 1, 0, 2, 0, TOGGLE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 14, 1, 0, 2, 0, TOGGLE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 15, 1, 0, 2, 0, TOGGLE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 16, 1, 0, 2, 0, TOGGLE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 17, 1, 0, 2, 0, TOGGLE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 18, 1, 0, 2, 0, TOGGLE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 19, 1, 0, 2, 0, TOGGLE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 20, 1, 0, 2, 0, TOGGLE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 21, 1, 0, 2, 0, TOGGLE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 22, 1, 0, 2, 0, TOGGLE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 23, 1, 0, 2, 0, TOGGLE_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
start_vector(0, 2, 256, 256);
end_vector();
start_vector(1, 1, 0, 256);
end_vector();
start_vector(16, 1, 0, 256);
end_vector();
add_seq_loc(0, 1, SEQ_NO_FLAG);
add_seq_loc(1, 1, SEQ_NO_FLAG);
add_seq_loc(16, 16, SEQ_NO_FLAG);
add_vect_cmd(0, 0, PROG_VCEOFF_FLAG+PROG_NOP_FLAG);
add_vect_cmd(1, 0, PROG_NOP_FLAG);
add_vect_cmd(2, 0, PROG_NOP_FLAG);
add_jmp_cmd(3, 1, 16, PROG_NOP_FLAG);
add_jmp_cmd(16, 16, 16, PROG_VCEON_FLAG);
end_digital();
