init_digital();
set_fclks_per_vector_pair(2);
set_driver_range(0.2, 3.5);
set_slew_rate(225);
set_chan_drv(mod_id, slot, 0, 1, 0, 2, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
start_vector(0, 2, 256, 256);
end_vector();
start_vector(1, 1, 0, 256);
end_vector();
start_vector(16, 1, 0, 256);
set_driver(mod_id, slot, 0, 0, ZERO_NUM);
end_vector();
start_vector(17, 1, 0, 256);
set_driver(mod_id, slot, 0, 0, TOGGLE_NUM);
end_vector();
add_seq_loc(0, 1, SEQ_NO_FLAG);
add_seq_loc(1, 1, SEQ_NO_FLAG);
add_seq_loc(2, 1, SEQ_NO_FLAG);
add_seq_loc(3, 1, SEQ_NO_FLAG);
add_seq_loc(4, 1, SEQ_NO_FLAG);
add_seq_loc(5, 1, SEQ_NO_FLAG);
add_seq_loc(6, 1, SEQ_NO_FLAG);
add_seq_loc(7, 1, SEQ_NO_FLAG);
add_seq_loc(8, 1, SEQ_NO_FLAG);
add_seq_loc(9, 1, SEQ_NO_FLAG);
add_seq_loc(10, 1, SEQ_NO_FLAG);
add_seq_loc(11, 1, SEQ_NO_FLAG);
add_seq_loc(12, 1, SEQ_NO_FLAG);
add_seq_loc(13, 1, SEQ_NO_FLAG);
add_seq_loc(14, 1, SEQ_NO_FLAG);
add_seq_loc(15, 1, SEQ_NO_FLAG);
add_seq_loc(16, 16, SEQ_NO_FLAG);
add_seq_loc(17, 17, SEQ_NO_FLAG);
add_vect_cmd(0, 0, PROG_VCEOFF_FLAG+PROG_NOP_FLAG);
add_vect_cmd(1, 0, PROG_VCEOFF_FLAG+PROG_NOP_FLAG);
add_vect_cmd(2, 0, PROG_VCEOFF_FLAG+PROG_NOP_FLAG);
add_jmp_cmd(3, 0, 16, PROG_VCEOFF_FLAG+PROG_NOP_FLAG);
add_vect_cmd(16, 16, PROG_VCEON_FLAG);
add_jmp_cmd(17, 17, 17, PROG_VCEOFF_FLAG);
add_vect_cmd(18, 0, PROG_VCEOFF_FLAG);
add_sls_cmd(19, 0, 12, PROG_VCEOFF_FLAG+PROG_NOP_FLAG);
add_vect_cmd(20, 0, PROG_VCEOFF_FLAG+PROG_NOP_FLAG);
add_vect_cmd(21, 0, PROG_VCEOFF_FLAG+PROG_NOP_FLAG+PROG_HALT_FLAG);
add_sls_cmd(22, 0, 2, PROG_VCEOFF_FLAG+PROG_NOP_FLAG);
end_digital();
