init_digital();
set_fclks_per_vector_pair(2);
set_driver_range(0.2, 3.5);
set_receiver_range(0.8, 2);
set_slew_rate(275);
set_chan_drv(mod_id, slot, 0, 1, 0, 2, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 1, 1, 0, 2, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 2, 1, 0, 2, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 3, 1, 0, 2, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 4, 1, 0, 2, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 5, 1, 0, 2, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 6, 1, 0, 2, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 7, 1, 0, 2, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_rcv(mod_id, slot, 0, 1, 65, 2, 65, ONE_TRI_NUM, PULL_UNUSED, CLAMP_UNUSED);
set_chan_rcv(mod_id, slot, 1, 1, 65, 2, 65, ONE_TRI_NUM, PULL_UNUSED, CLAMP_UNUSED);
set_chan_rcv(mod_id, slot, 2, 1, 65, 2, 65, ONE_TRI_NUM, PULL_UNUSED, CLAMP_UNUSED);
set_chan_rcv(mod_id, slot, 3, 1, 65, 2, 65, ONE_TRI_NUM, PULL_UNUSED, CLAMP_UNUSED);
set_chan_rcv(mod_id, slot, 4, 1, 65, 2, 65, ONE_TRI_NUM, PULL_UNUSED, CLAMP_UNUSED);
set_chan_rcv(mod_id, slot, 5, 1, 65, 2, 65, ONE_TRI_NUM, PULL_UNUSED, CLAMP_UNUSED);
set_chan_rcv(mod_id, slot, 6, 1, 65, 2, 65, ONE_TRI_NUM, PULL_UNUSED, CLAMP_UNUSED);
set_chan_rcv(mod_id, slot, 7, 1, 65, 2, 65, ONE_TRI_NUM, PULL_UNUSED, CLAMP_UNUSED);
start_vector(0, 2, 256, 256);
end_vector();
start_vector(1, 1, 0, 256);
end_vector();
start_vector(2, 1, 0, 256);
end_vector();
start_vector(16, 1, 0, 256);
set_driver(mod_id, slot, 0, 0, ONE_NUM);
set_driver(mod_id, slot, 1, 0, ONE_NUM);
set_driver(mod_id, slot, 2, 0, ONE_NUM);
set_driver(mod_id, slot, 3, 0, ONE_NUM);
set_driver(mod_id, slot, 4, 0, ONE_NUM);
set_driver(mod_id, slot, 5, 0, ONE_NUM);
set_driver(mod_id, slot, 6, 0, ONE_NUM);
set_driver(mod_id, slot, 7, 0, ONE_NUM);
end_vector();
start_vector(17, 1, 0, 256);
set_driver(mod_id, slot, 0, 0, ZERO_NUM);
set_driver(mod_id, slot, 1, 0, ZERO_NUM);
set_driver(mod_id, slot, 2, 0, ZERO_NUM);
set_driver(mod_id, slot, 3, 0, ZERO_NUM);
set_driver(mod_id, slot, 4, 0, ZERO_NUM);
set_driver(mod_id, slot, 5, 0, ZERO_NUM);
set_driver(mod_id, slot, 6, 0, ZERO_NUM);
set_driver(mod_id, slot, 7, 0, ZERO_NUM);
set_receiver(mod_id, slot, 0, 0, ZERO_NUM);
set_receiver(mod_id, slot, 1, 0, ZERO_NUM);
set_receiver(mod_id, slot, 2, 0, ZERO_NUM);
set_receiver(mod_id, slot, 3, 0, ZERO_NUM);
set_receiver(mod_id, slot, 4, 0, ZERO_NUM);
set_receiver(mod_id, slot, 5, 0, ZERO_NUM);
set_receiver(mod_id, slot, 6, 0, ZERO_NUM);
set_receiver(mod_id, slot, 7, 0, ZERO_NUM);
end_vector();
add_seq_loc(0, 1, SEQ_NO_FLAG);
add_seq_loc(1, 2, SEQ_NO_FLAG);
add_seq_loc(2, 1, SEQ_NO_FLAG);
add_seq_loc(3, 2, SEQ_NO_FLAG);
add_seq_loc(4, 1, SEQ_NO_FLAG);
add_seq_loc(5, 2, SEQ_NO_FLAG);
add_seq_loc(6, 1, SEQ_NO_FLAG);
add_seq_loc(7, 2, SEQ_NO_FLAG);
add_seq_loc(8, 1, SEQ_NO_FLAG);
add_seq_loc(9, 2, SEQ_NO_FLAG);
add_seq_loc(10, 1, SEQ_NO_FLAG);
add_seq_loc(11, 2, SEQ_NO_FLAG);
add_seq_loc(12, 1, SEQ_NO_FLAG);
add_seq_loc(13, 2, SEQ_NO_FLAG);
add_seq_loc(14, 1, SEQ_NO_FLAG);
add_seq_loc(15, 2, SEQ_NO_FLAG);
add_seq_loc(16, 16, SEQ_NO_FLAG);
add_seq_loc(17, 17, SEQ_NO_FLAG);
add_vect_cmd(0, 0, PROG_VCEOFF_FLAG+PROG_NOP_FLAG);
add_vect_cmd(1, 1, PROG_NOP_FLAG);
add_vect_cmd(2, 0, PROG_NOP_FLAG);
add_jmp_cmd(3, 1, 16, PROG_NOP_FLAG);
add_vect_cmd(16, 16, PROG_VCEON_FLAG);
add_vect_cmd(17, 17, PROG_NO_FLAG);
add_vect_cmd(18, 16, PROG_NO_FLAG);
add_sls_cmd(19, 0, 7, PROG_NOP_FLAG);
add_vect_cmd(20, 13, PROG_VCEOFF_FLAG+PROG_NOP_FLAG+PROG_HALT_FLAG);
add_vect_cmd(21, 14, PROG_NOP_FLAG);
add_vect_cmd(22, 15, PROG_NOP_FLAG);
end_digital();
