init_digital();
set_fclks_per_vector_pair(4);
set_driver_range(0, 5);
set_slew_rate(275);
set_chan_drv(mod_id, slot, 0, 1, 0, 3, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 1, 1, 0, 3, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 2, 1, 0, 3, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 3, 1, 0, 3, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 4, 1, 0, 3, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 5, 1, 0, 3, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 6, 1, 0, 3, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 7, 1, 0, 3, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 8, 1, 0, 3, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 9, 1, 0, 3, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 10, 1, 0, 3, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 11, 1, 0, 3, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 12, 1, 0, 3, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 13, 1, 0, 3, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 14, 1, 0, 3, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
set_chan_drv(mod_id, slot, 15, 1, 0, 3, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0 );
start_vector(0, 2, 256, 256);
end_vector();
start_vector(1, 2, 0, 1);
end_vector();
start_vector(16, 2, 0, 1);
set_driver(mod_id, slot, 0, 0, ONE_NUM);
set_driver(mod_id, slot, 1, 0, ONE_NUM);
set_driver(mod_id, slot, 2, 0, ONE_NUM);
set_driver(mod_id, slot, 3, 0, ONE_NUM);
set_driver(mod_id, slot, 4, 0, ONE_NUM);
set_driver(mod_id, slot, 5, 0, ONE_NUM);
set_driver(mod_id, slot, 6, 0, ONE_NUM);
set_driver(mod_id, slot, 7, 0, ONE_NUM);
set_driver(mod_id, slot, 8, 0, ONE_NUM);
set_driver(mod_id, slot, 9, 0, ONE_NUM);
set_driver(mod_id, slot, 10, 0, ONE_NUM);
set_driver(mod_id, slot, 11, 0, ONE_NUM);
set_driver(mod_id, slot, 12, 0, ONE_NUM);
set_driver(mod_id, slot, 13, 0, ONE_NUM);
set_driver(mod_id, slot, 14, 0, ONE_NUM);
set_driver(mod_id, slot, 15, 0, ONE_NUM);
end_vector();
start_vector(17, 196, 0, 1);
set_driver(mod_id, slot, 0, 0, ZERO_NUM);
set_driver(mod_id, slot, 1, 0, ZERO_NUM);
set_driver(mod_id, slot, 2, 0, ZERO_NUM);
set_driver(mod_id, slot, 3, 0, ZERO_NUM);
set_driver(mod_id, slot, 4, 0, ZERO_NUM);
set_driver(mod_id, slot, 5, 0, ZERO_NUM);
set_driver(mod_id, slot, 6, 0, ZERO_NUM);
set_driver(mod_id, slot, 7, 0, ZERO_NUM);
set_driver(mod_id, slot, 8, 0, ZERO_NUM);
set_driver(mod_id, slot, 9, 0, ZERO_NUM);
set_driver(mod_id, slot, 10, 0, ZERO_NUM);
set_driver(mod_id, slot, 11, 0, ZERO_NUM);
set_driver(mod_id, slot, 12, 0, ZERO_NUM);
set_driver(mod_id, slot, 13, 0, ZERO_NUM);
set_driver(mod_id, slot, 14, 0, ZERO_NUM);
set_driver(mod_id, slot, 15, 0, ZERO_NUM);
end_vector();
add_seq_loc(0, 1, SEQ_NO_FLAG);
add_seq_loc(1, 1, SEQ_NO_FLAG);
add_seq_loc(2, 1, SEQ_NO_FLAG);
add_seq_loc(3, 1, SEQ_NO_FLAG);
add_seq_loc(4, 1, SEQ_NO_FLAG);
add_seq_loc(5, 1, SEQ_NO_FLAG);
add_seq_loc(6, 1, SEQ_NO_FLAG);
add_seq_loc(7, 1, SEQ_NO_FLAG);
add_seq_loc(8, 1, SEQ_NO_FLAG);
add_seq_loc(9, 1, SEQ_NO_FLAG);
add_seq_loc(10, 1, SEQ_NO_FLAG);
add_seq_loc(11, 1, SEQ_NO_FLAG);
add_seq_loc(12, 1, SEQ_NO_FLAG);
add_seq_loc(13, 1, SEQ_NO_FLAG);
add_seq_loc(14, 1, SEQ_NO_FLAG);
add_seq_loc(15, 1, SEQ_NO_FLAG);
add_seq_loc(16, 16, SEQ_NO_FLAG);
add_seq_loc(17, 17, SEQ_NO_FLAG);
add_vect_cmd(0, 0, PROG_VCEOFF_FLAG+PROG_NOP_FLAG);
add_vect_cmd(1, 0, PROG_NOP_FLAG);
add_vect_cmd(2, 0, PROG_NOP_FLAG);
add_jmp_cmd(3, 0, 16, PROG_NOP_FLAG);
add_vect_cmd(16, 16, PROG_VCEON_FLAG);
add_vect_cmd(17, 17, PROG_NO_FLAG);
add_jmp_cmd(18, 17, 16, PROG_NO_FLAG);
add_sls_cmd(19, 0, 13, PROG_NOP_FLAG);
add_vect_cmd(20, 0, PROG_VCEOFF_FLAG+PROG_NOP_FLAG+PROG_HALT_FLAG);
add_vect_cmd(21, 0, PROG_NOP_FLAG);
add_vect_cmd(22, 0, PROG_NOP_FLAG);
end_digital();
