init_digital();
set_fclks_per_vector_pair(4);
set_driver_range(0.000000,3.500000);
set_slew_rate(275);
set_chan_drv(mod_id, slot, 0, 1, 0, 3, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 1, 1, 0, 3, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 2, 1, 0, 3, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 3, 1, 0, 3, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 4, 1, 0, 3, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 5, 1, 0, 3, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 6, 1, 0, 3, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 7, 1, 0, 3, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
output_drv_and_rcv_enable();
start_vector(0, 2, 256, 256);
end_vector();
start_vector(1, 2, 0, 1);
end_vector();
start_vector(16, 250, 0, 1);
set_driver(mod_id, slot, 0, 16, ONE_NUM);
set_driver(mod_id, slot, 1, 16, ONE_NUM);
set_driver(mod_id, slot, 2, 16, ONE_NUM);
set_driver(mod_id, slot, 3, 16, ONE_NUM);
set_driver(mod_id, slot, 4, 16, ONE_NUM);
set_driver(mod_id, slot, 5, 16, ONE_NUM);
set_driver(mod_id, slot, 6, 16, ONE_NUM);
set_driver(mod_id, slot, 7, 16, ONE_NUM);
end_vector();
start_vector(17, 250, 0, 1);
set_driver(mod_id, slot, 0, 17, ZERO_NUM);
set_driver(mod_id, slot, 1, 17, ZERO_NUM);
set_driver(mod_id, slot, 2, 17, ZERO_NUM);
set_driver(mod_id, slot, 3, 17, ZERO_NUM);
set_driver(mod_id, slot, 4, 17, ZERO_NUM);
set_driver(mod_id, slot, 5, 17, ZERO_NUM);
set_driver(mod_id, slot, 6, 17, ZERO_NUM);
set_driver(mod_id, slot, 7, 17, ZERO_NUM);
end_vector();
vmcEndVectorSection();
add_seq_loc(0, 1, SEQ_NO_FLAG);
add_seq_loc(1, 1, SEQ_NO_FLAG);
add_seq_loc(2, 1, SEQ_NO_FLAG);
add_seq_loc(3, 1, SEQ_NO_FLAG);
add_seq_loc(4, 1, SEQ_NO_FLAG);
add_seq_loc(5, 1, SEQ_NO_FLAG);
add_seq_loc(6, 1, SEQ_NO_FLAG);
add_seq_loc(7, 1, SEQ_NO_FLAG);
add_seq_loc(8, 1, SEQ_NO_FLAG);
add_seq_loc(9, 1, SEQ_NO_FLAG);
add_seq_loc(10, 1, SEQ_NO_FLAG);
add_seq_loc(11, 1, SEQ_NO_FLAG);
add_seq_loc(12, 1, SEQ_NO_FLAG);
add_seq_loc(13, 1, SEQ_NO_FLAG);
add_seq_loc(14, 1, SEQ_NO_FLAG);
add_seq_loc(15, 1, SEQ_NO_FLAG);
add_seq_loc(16, 16, SEQ_NO_FLAG);
add_seq_loc(17, 16, SEQ_NO_FLAG);
add_seq_loc(18, 16, SEQ_NO_FLAG);
add_seq_loc(19, 16, SEQ_NO_FLAG);
add_seq_loc(20, 16, SEQ_NO_FLAG);
add_seq_loc(21, 16, SEQ_NO_FLAG);
add_seq_loc(22, 16, SEQ_NO_FLAG);
add_seq_loc(23, 16, SEQ_NO_FLAG);
add_seq_loc(24, 16, SEQ_NO_FLAG);
add_seq_loc(25, 16, SEQ_NO_FLAG);
add_seq_loc(26, 17, SEQ_NO_FLAG);
add_vect_cmd(0, 0, PROG_VCEOFF_FLAG+PROG_NOP_FLAG);
add_vect_cmd(1, 0, PROG_NOP_FLAG);
add_vect_cmd(2, 0, PROG_NOP_FLAG);
add_jmp_cmd(3, 0, 16, PROG_NOP_FLAG);
add_vect_cmd(16, 26, PROG_VCEON_FLAG);
add_vect_cmd(17, 26, PROG_NO_FLAG);
add_vect_cmd(18, 26, PROG_NO_FLAG);
add_vect_cmd(19, 26, PROG_NO_FLAG);
add_sls_cmd(20, 16, 10, PROG_NO_FLAG);
add_sls_cmd(21, 16, 10, PROG_NO_FLAG);
add_sls_cmd(22, 16, 10, PROG_NO_FLAG);
add_sls_cmd(23, 16, 10, PROG_NO_FLAG);
add_sls_cmd(24, 16, 10, PROG_NO_FLAG);
add_sls_cmd(25, 16, 10, PROG_NO_FLAG);
add_sls_cmd(26, 16, 10, PROG_NO_FLAG);
add_sls_cmd(27, 16, 10, PROG_NO_FLAG);
add_sls_cmd(28, 16, 10, PROG_NO_FLAG);
add_sls_cmd(29, 16, 10, PROG_NO_FLAG);
add_sls_cmd(30, 16, 10, PROG_NO_FLAG);
add_sls_cmd(31, 16, 10, PROG_NO_FLAG);
add_sls_cmd(32, 16, 10, PROG_NO_FLAG);
add_sls_cmd(33, 16, 10, PROG_NO_FLAG);
add_sls_cmd(34, 16, 10, PROG_NO_FLAG);
add_sls_cmd(35, 16, 10, PROG_NO_FLAG);
add_sls_cmd(36, 16, 10, PROG_NO_FLAG);
add_sls_cmd(37, 16, 10, PROG_NO_FLAG);
add_sls_cmd(38, 16, 10, PROG_NO_FLAG);
add_sls_cmd(39, 16, 10, PROG_NO_FLAG);
add_vect_cmd(40, 26, PROG_NO_FLAG);
add_sls_cmd(41, 0, 13, PROG_NOP_FLAG);
add_vect_cmd(42, 0, PROG_VCEOFF_FLAG+PROG_NOP_FLAG+PROG_HALT_FLAG);
add_vect_cmd(43, 0, PROG_NOP_FLAG);
add_vect_cmd(44, 0, PROG_NOP_FLAG);
end_digital();
