init_digital();
set_fclks_per_vector_pair(4);
set_driver_range(0.000000,0.000000);
set_slew_rate(275);
set_chan_drv(mod_id, slot, 1, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 2, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 3, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 4, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 5, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 6, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 7, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 8, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 9, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 10, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 11, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 12, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 13, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 14, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 15, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 16, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 17, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 18, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 21, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 22, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 23, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 24, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 25, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 26, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 27, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 28, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 29, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 30, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 31, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 32, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 33, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 34, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 35, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 36, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 37, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 38, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 41, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 42, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 43, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 44, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 45, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 46, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 47, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 48, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 49, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 50, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 51, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 52, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 53, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 54, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 55, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 56, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 57, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 58, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 61, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 62, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 63, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 64, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 65, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 66, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 67, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 68, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 69, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 70, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 71, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 72, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 73, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 74, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 75, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 76, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 77, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 78, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 101, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 102, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 103, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 104, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 105, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 106, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 107, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 108, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 109, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 110, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 111, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 112, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 113, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 114, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 115, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 116, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 117, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 118, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 121, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 122, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 123, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 124, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 125, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 126, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 127, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 128, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 129, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 130, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 131, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 132, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 133, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 134, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 135, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 136, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 137, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 138, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 141, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 142, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 143, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 144, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 145, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 146, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 147, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 148, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 149, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 150, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 151, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 152, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 153, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 154, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 155, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 156, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 157, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 158, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 161, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 162, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 163, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 164, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 165, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 166, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 167, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 168, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 169, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 170, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 171, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 172, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 173, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 174, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 175, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 176, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 177, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_drv(mod_id, slot, 178, 1, 0, 3, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
output_drv_and_rcv_enable();
start_vector(0, 2, 256, 256);
end_vector();
start_vector(1, 2, 0, 1);
end_vector();
start_vector(16, 4, 0, 1);
set_driver(mod_id, slot, 1, 16, ONE_NUM);
set_driver(mod_id, slot, 2, 16, ONE_NUM);
set_driver(mod_id, slot, 3, 16, ONE_NUM);
set_driver(mod_id, slot, 4, 16, ONE_NUM);
set_driver(mod_id, slot, 5, 16, ONE_NUM);
end_vector();
start_vector(17, 4, 0, 1);
set_driver(mod_id, slot, 1, 17, ZERO_NUM);
set_driver(mod_id, slot, 2, 17, ZERO_NUM);
set_driver(mod_id, slot, 3, 17, ZERO_NUM);
set_driver(mod_id, slot, 4, 17, ZERO_NUM);
set_driver(mod_id, slot, 5, 17, ZERO_NUM);
end_vector();
vmcEndVectorSection();
add_seq_loc(0, 1, SEQ_NO_FLAG);
add_seq_loc(1, 1, SEQ_NO_FLAG);
add_seq_loc(2, 1, SEQ_NO_FLAG);
add_seq_loc(3, 1, SEQ_NO_FLAG);
add_seq_loc(4, 1, SEQ_NO_FLAG);
add_seq_loc(5, 1, SEQ_NO_FLAG);
add_seq_loc(6, 1, SEQ_NO_FLAG);
add_seq_loc(7, 1, SEQ_NO_FLAG);
add_seq_loc(8, 1, SEQ_NO_FLAG);
add_seq_loc(9, 1, SEQ_NO_FLAG);
add_seq_loc(10, 1, SEQ_NO_FLAG);
add_seq_loc(11, 1, SEQ_NO_FLAG);
add_seq_loc(12, 1, SEQ_NO_FLAG);
add_seq_loc(13, 1, SEQ_NO_FLAG);
add_seq_loc(14, 1, SEQ_NO_FLAG);
add_seq_loc(15, 1, SEQ_NO_FLAG);
add_seq_loc(16, 16, SEQ_NO_FLAG);
add_seq_loc(17, 17, SEQ_NO_FLAG);
add_vect_cmd(0, 0, PROG_VCEOFF_FLAG+PROG_NOP_FLAG);
add_vect_cmd(1, 0, PROG_NOP_FLAG);
add_vect_cmd(2, 0, PROG_NOP_FLAG);
add_jmp_cmd(3, 0, 16, PROG_NOP_FLAG);
add_vect_cmd(16, 16, PROG_VCEON_FLAG);
add_vect_cmd(17, 16, PROG_NO_FLAG);
add_jmp_cmd(18, 17, 16, PROG_NO_FLAG);
add_vect_cmd(19, 0, PROG_VCEON_FLAG);
add_sls_cmd(20, 0, 13, PROG_NOP_FLAG);
add_vect_cmd(21, 0, PROG_VCEOFF_FLAG+PROG_NOP_FLAG+PROG_HALT_FLAG);
add_vect_cmd(22, 0, PROG_NOP_FLAG);
add_vect_cmd(23, 0, PROG_NOP_FLAG);
end_digital();
