init_digital();
set_fclks_per_vector_pair(2);
set_chan_drv(mod_id, slot, 0, 1, 0, 2, 0, ONE_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
output_drv_and_rcv_enable();
start_vector(0, 2, 256, 256);
end_vector();
start_vector(1, 1, 0, 256);
end_vector();
start_vector(2, 1, 0, 256);
end_vector();
start_vector(16, 2, 0, 1);
end_vector();
vmcEndVectorSection();
add_seq_loc(0, 1, SEQ_NO_FLAG);
add_seq_loc(1, 2, SEQ_NO_FLAG);
add_seq_loc(2, 1, SEQ_NO_FLAG);
add_seq_loc(3, 2, SEQ_NO_FLAG);
add_seq_loc(4, 1, SEQ_NO_FLAG);
add_seq_loc(5, 2, SEQ_NO_FLAG);
add_seq_loc(6, 1, SEQ_NO_FLAG);
add_seq_loc(7, 2, SEQ_NO_FLAG);
add_seq_loc(8, 1, SEQ_NO_FLAG);
add_seq_loc(9, 2, SEQ_NO_FLAG);
add_seq_loc(10, 1, SEQ_NO_FLAG);
add_seq_loc(11, 2, SEQ_NO_FLAG);
add_seq_loc(12, 1, SEQ_NO_FLAG);
add_seq_loc(13, 2, SEQ_NO_FLAG);
add_seq_loc(14, 1, SEQ_NO_FLAG);
add_seq_loc(15, 2, SEQ_NO_FLAG);
add_seq_loc(16, 16, SEQ_NO_FLAG);
add_seq_loc(17, 16, SEQ_NO_FLAG);
add_seq_loc(18, 16, SEQ_NO_FLAG);
add_seq_loc(19, 16, SEQ_NO_FLAG);
add_seq_loc(20, 16, SEQ_NO_FLAG);
add_seq_loc(21, 16, SEQ_NO_FLAG);
add_seq_loc(22, 16, SEQ_NO_FLAG);
add_seq_loc(23, 16, SEQ_NO_FLAG);
add_seq_loc(24, 16, SEQ_NO_FLAG);
add_seq_loc(25, 16, SEQ_NO_FLAG);
add_seq_loc(26, 16, SEQ_NO_FLAG);
add_seq_loc(27, 16, SEQ_NO_FLAG);
add_seq_loc(28, 16, SEQ_NO_FLAG);
add_seq_loc(29, 16, SEQ_NO_FLAG);
add_seq_loc(30, 16, SEQ_NO_FLAG);
add_seq_loc(31, 16, SEQ_NO_FLAG);
add_seq_loc(32, 16, SEQ_NO_FLAG);
add_seq_loc(33, 16, SEQ_NO_FLAG);
add_seq_loc(34, 16, SEQ_NO_FLAG);
add_seq_loc(35, 16, SEQ_NO_FLAG);
add_seq_loc(36, 16, SEQ_NO_FLAG);
add_seq_loc(37, 16, SEQ_NO_FLAG);
add_seq_loc(38, 16, SEQ_NO_FLAG);
add_seq_loc(39, 16, SEQ_NO_FLAG);
add_seq_loc(40, 16, SEQ_NO_FLAG);
add_seq_loc(41, 16, SEQ_NO_FLAG);
add_vect_cmd(0, 0, PROG_VCEOFF_FLAG+PROG_NOP_FLAG);
add_vect_cmd(1, 1, PROG_NOP_FLAG);
add_vect_cmd(2, 0, PROG_NOP_FLAG);
add_jmp_cmd(3, 1, 16, PROG_NOP_FLAG);
add_sls_cmd(16, 16, 19, PROG_VCEON_FLAG+PROG_NOP_FLAG);
add_vect_cmd(17, 16, PROG_SCE_FLAG+PROG_FE_FLAG);
add_sls_cmd(18, 16, 8, PROG_NOP_FLAG);
add_sls_cmd(19, 0, 13, PROG_NOP_FLAG);
add_vect_cmd(20, 13, PROG_VCEOFF_FLAG+PROG_NOP_FLAG+PROG_HALT_FLAG);
add_vect_cmd(21, 14, PROG_NOP_FLAG);
add_vect_cmd(22, 15, PROG_NOP_FLAG);
end_digital();
