/* Header for module mt9000, generated by p2c */
#ifndef MT9000_P_H
#define MT9000_P_H

/*
        * This module contains all of the "assembly" routines. To add an
        * assembly routine:
        *
        * 1. Add a new opcode
        * -files opcodes.p opcodes.x
        *
        * 2. Add the assembly routine
        *-files vth.p vth.x
        *
        * 3. Add a new trace routine
        * -files trc/src/trc.p trc/src/trc.x
        *
        * 4. Add the new parse routine to panel
        *-files panel/src/parse.p panel/src/parse.x panel/src/panel.p
        *
*/

/*
        * To add a new opcode
        * 1. Add the new opcode_LEX to parse.x
        * 2. Increment MAX_COMMAND in the procedure parse_command
        * 3. Add new opcode to the parse table
        * 4. Add the new parse routine and its external
        * 5. Add call to parse routine in panel.p
*/
#include "../../../u/src/hdw_p.h"
#include "../../../dgn/src/dgnconfig_p.h"
#include "../../../dgn/src/termio_p.h"
#include "../../../dgn/src/testdec_p.h"
#include "../../../dgn/src/execsup_p.h"
#include "../../../vth/src/capasm_p.h"
#include "../../../vth/src/macasm_p.h"
#include "../../../vth/src/aimasm_p.h"
#include "../../../vth/src/pinasm_p.h"
#include "../../../vth/src/result_p.h"
#include "../../../dgn/src/strdec.h"
#include "../../../vth/src/vth_p.h"
#include "../../../vth/src/vthsup_p.h"
#include "../../../vth/src/standard_p.h"
#include "../../../vth/src/strings_p.h"
#include "../../../dgn/src/limits_p.h"
#include "../../../dgn/src/convert.h"
#include "mtglobal_p.h"

void t9000(void);
void t9001(int mod_id, int slot);
void t9002(int mod_id, int slot);
void t9003(int mod_id, int slot);
void t9004(void);
void t9005(void);
void t9006(int *ms_list);
void t9007(void);
void t9008(void);
//void t9009(void);//added sri 9th August 2007
void t9010(int mod_id, int slot);
void t9011(int mod_id, int slot);
void t9012(int mod_id, int slot);
void t9015(void);
void t9016(int mod_id, int slot);
void t9020(int mod_id, int slot);
void t9021(int mod_id, int slot);
void t9030(int mod_id, int slot);
void t9031(int mod_id, int slot);
void t9032(int mod_id, int slot);
void t9033(int mod_id, int slot);
void t9034(int mod_id, int slot);
void t9035(int mod_id, int slot);
void t9040(int mod_id, int slot);
void t9041(int mod_id, int slot);
void t9042(int mod_id, int slot);
void t9043(int mod_id, int slot);
void t9044(int mod_id, int slot);
void t9047(int mod_id, int slot);
void t9048(void);
void t9049(void);
void t9050(int mod_id, int slot);
void t9052(int mod_id, int slot);
void t9053(int mod_id, int slot);
void t9055(int mod_id, int slot);
void t9056(int mod_id, int slot);
void t9060(int mod_id, int slot);
void t9061(int mod_id, int slot);
void t9062(int mod_id, int slot);
void t9065(int mod_id, int slot);
void t9070(int mod_id, int slot);
void t9071(int mod_id, int slot);
void t9072(int mod_id, int slot);
void t9075(int mod_id, int slot);
void t9080(int mod_id, int slot);
void t9081(int mod_id, int slot);
void t9082(int mod_id, int slot);
void t9090(int mod_id, int slot);
void t9091(int mod_id, int slot);
void t9092(int mod_id, int slot);
void t9095(int mod_id, int slot);
void t9100(int mod_id, int slot);
void t9101(int mod_id, int slot);
void t9102(int mod_id, int slot);
void t9103(int mod_id, int slot);
void t9104(int mod_id, int slot);
void t9105(int mod_id, int slot);
void t9106(int mod_id, int slot);
void t9107(int mod_id, int slot);
void t9111(int mod_id, int slot);
void t9120(int mod_id, int slot);
void t9121(int mod_id, int slot);
void t9122(int mod_id, int slot);
void t9125(int *ms_list);
void t9126(int *ms_list);
void t9127(int *ms_list);
void t9129(int mod_id, int slot);
void t9130(int mod_id, int slot);
void t9131(int mod_id, int slot);
void t9132(int mod_id, int slot);
void t9133(int mod_id, int slot);
void t9134(int mod_id, int slot);
void t9135(int mod_id, int slot);
void t9136(int mod_id, int slot);
void t9137(int mod_id, int slot);
void t9138(int mod_id, int slot);
void t9140(int mod_id, int slot);
void t9141(int mod_id, int slot);
void t9142(int mod_id, int slot);
void t9143(int mod_id, int slot);
void t9144(int mod_id, int slot);
void t9145(int mod_id, int slot);
void t9146(int mod_id, int slot);
void t9147(int mod_id, int slot);
void t9148(int mod_id, int slot);
void t9149(int mod_id, int slot);
void t9150(int mod_id, int slot);
void t9151(int mod_id, int slot);
void t9152(int mod_id, int slot);
void t9153(int mod_id, int slot);
void t9155(int mod_id, int slot);
void t9156(int mod_id, int slot);
void t9160(int mod_id, int slot);
void t9161(int mod_id, int slot);
void t9162(int mod_id, int slot);
void t9165(int mod_id, int slot);
void t9166(int mod_id, int slot);
void t9167(int mod_id, int slot);
void t9170(int mod_id, int slot);
void t9171(int mod_id, int slot);
void t9172(int mod_id, int slot);
void t9173(int mod_id, int slot);
void t9180(int mod_id, int slot);
void t9181(int mod_id, int slot);
void t9182(int mod_id, int slot);
void t9183(int mod_id, int slot);
void t9184(int mod_id, int slot);
void t9185(int mod_id, int slot);
void t9186(int mod_id, int slot);
void t9187(int mod_id, int slot);
void t9188(int mod_id, int slot);
void t9189(int mod_id, int slot);
void t9191(void);
void t9195(void);
void t9196(void);
void t9200(int mod_id, int slot);
void t9201(int mod_id, int slot);
void t9205(int mod_id, int slot);
void t9206(int mod_id, int slot);
void t9207(int mod_id, int slot);
void t9208(int mod_id, int slot);
void t9209(int mod_id, int slot);
void t9210(int mod_id, int slot);
void t9211(int mod_id, int slot);
void t9217(int mod_id, int slot);
void t9220(int mod_id, int slot);
void t9221(int mod_id, int slot);
void t9230(int mod_id, int slot);
void t9231(int mod_id, int slot);
void t9232(int mod_id, int slot);
void t9240(int mod_id, int slot);
void t9241(int mod_id, int slot);
void t9242(int mod_id, int slot);
void t9243(int mod_id, int slot);
void t9244(int mod_id, int slot);
void t9245(int mod_id, int slot);
void t9246(int mod_id, int slot);
void t9247(int mod_id, int slot);
void t9248(int mod_id, int slot);
void t9249(int mod_id, int slot);
void t9233(int mod_id, int slot);
void t9234(int mod_id, int slot);
void t9235(int mod_id, int slot);
void t9236(int mod_id, int slot);
void t9237(int mod_id, int slot);
void t9238(int mod_id, int slot);
void t9239(int mod_id, int slot);
void t9222(int mod_id, int slot);
void t9223(int mod_id, int slot);
void t9224(int mod_id, int slot);
void t9225(int mod_id, int slot);
void t9226(int mod_id, int slot);


#endif
