/* Header for module mt9500, generated by p2c */
#ifndef MT9500_P_H
#define MT9500_P_H

/*
        * This module contains all of the "assembly" routines. To add an
        * assembly routine:
        *
        * 1. Add a new opcode
        * -files opcodes.p opcodes.x
        *
        * 2. Add the assembly routine
        *-files vth.p vth.x
        *
        * 3. Add a new trace routine
        * -files trc/src/trc.p trc/src/trc.x
        *
        * 4. Add the new parse routine to panel
        *-files panel/src/parse.p panel/src/parse.x panel/src/panel.p
        *
*/

/*
        * To add a new opcode
        * 1. Add the new opcode_LEX to parse.x
        * 2. Increment MAX_COMMAND in the procedure parse_command
        * 3. Add new opcode to the parse table
        * 4. Add the new parse routine and its external
        * 5. Add call to parse routine in panel.p
*/
#include "../../../u/src/hdw_p.h"
#include "../../../dgn/src/dgnconfig_p.h"
#include "../../../dgn/src/termio_p.h"
#include "../../../dgn/src/testdec_p.h"
#include "../../../dgn/src/execsup_p.h"
#include "../../../vth/src/capasm_p.h"
#include "../../../vth/src/macasm_p.h"
#include "../../../vth/src/aimasm_p.h"
#include "../../../vth/src/pinasm_p.h"
#include "../../../vth/src/result_p.h"
#include "../../../dgn/src/strdec.h"
#include "../../../vth/src/vth_p.h"
#include "../../../vth/src/vthsup_p.h"
#include "../../../vth/src/standard_p.h"
#include "../../../vth/src/strings_p.h"
#include "mtglobal_p.h"

void t9500(void);
void t9605(int mod_id, int slot);
void t9620(int mod_id, int slot);
void t9671(int mod_id, int slot);
void t9685(int mod_id, int slot);
void t9700(int mod_id, int slot);
void t9701(int mod_id, int slot);
void t9705(int mod_id, int slot);
void t9706(int mod_id, int slot);
void t9710(int mod_id, int slot);
void t9711(int mod_id, int slot);
void t9721(int mod_id, int slot);
void t9730(int mod_id, int slot);

#endif
