init_digital();
set_fclks_per_vector_pair(fclk_mode);
set_driver_range(0.000000,3.500000);
set_receiver_range(1.500000,1.500000);
set_chan_drv(mod_id, slot, 1, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 1, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 2, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 2, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 3, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 3, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 4, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 4, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 5, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 5, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 6, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 6, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 7, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 7, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 8, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 8, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 9, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 9, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 10, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 10, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 11, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 11, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 12, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 12, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 13, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 13, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 14, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 14, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 15, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 15, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 16, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 16, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 17, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 17, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 18, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 18, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 21, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 21, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 22, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 22, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 23, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 23, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 24, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 24, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 25, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 25, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 26, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 26, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 27, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 27, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 28, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 28, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 29, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 29, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 30, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 30, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 31, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 31, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 32, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 32, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 33, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 33, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 34, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 34, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 35, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 35, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 36, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 36, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 37, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 37, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 38, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 38, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 41, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 41, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 42, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 42, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 43, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 43, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 44, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 44, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 45, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 45, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 46, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 46, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 47, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 47, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 48, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 48, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 49, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 49, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 50, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 50, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 51, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 51, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 52, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 52, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 53, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 53, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 54, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 54, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 55, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 55, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 56, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 56, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 57, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 57, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 58, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 58, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 61, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 61, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 62, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 62, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 63, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 63, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 64, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 64, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 65, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 65, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 66, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 66, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 67, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 67, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 68, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 68, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 69, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 69, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 70, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 70, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 71, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 71, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 72, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 72, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 73, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 73, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 74, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 74, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 75, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 75, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 76, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 76, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 77, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 77, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 78, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 78, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 101, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 101, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 102, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 102, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 103, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 103, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 104, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 104, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 105, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 105, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 106, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 106, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 107, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 107, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 108, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 108, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 109, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 109, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 110, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 110, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 111, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 111, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 112, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 112, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 113, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 113, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 114, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 114, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 115, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 115, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 116, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 116, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 117, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 117, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 118, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 118, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 121, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 121, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 122, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 122, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 123, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 123, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 124, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 124, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 125, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 125, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 126, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 126, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 127, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 127, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 128, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 128, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 129, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 129, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 130, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 130, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 131, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 131, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 132, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 132, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 133, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 133, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 134, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 134, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 135, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 135, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 136, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 136, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 137, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 137, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 138, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 138, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 141, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 141, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 142, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 142, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 143, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 143, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 144, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 144, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 145, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 145, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 146, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 146, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 147, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 147, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 148, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 148, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 149, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 149, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 150, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 150, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 151, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 151, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 152, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 152, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 153, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 153, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 154, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 154, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 155, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 155, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 156, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 156, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 157, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 157, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 158, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 158, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 161, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 161, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 162, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 162, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 163, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 163, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 164, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 164, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 165, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 165, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 166, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 166, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 167, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 167, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 168, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 168, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 169, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 169, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 170, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 170, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 171, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 171, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 172, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 172, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 173, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 173, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 174, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 174, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 175, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 175, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 176, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 176, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 177, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 177, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
set_chan_drv(mod_id, slot, 178, 2, 0, 4, 0, KEEP_TRI_NUM, FLIP_FLOP_NUM, FLIP_FLOP_NUM, 0);
set_chan_rcv(mod_id, slot, 178, 2, 100, 4, 100, KEEP_TRI_NUM, PULL_UNUSED, RTERM_ON_NUM);
output_drv_and_rcv_enable();
start_vector(0, 2, 256, 256);
end_vector();
start_vector(1, 2, 0, 1);
end_vector();
start_vector(16, 2, 0, 1);
set_driver(mod_id, slot, 1, 16, ONE_NUM);
set_driver(mod_id, slot, 2, 16, ONE_NUM);
set_driver(mod_id, slot, 3, 16, ONE_NUM);
set_driver(mod_id, slot, 4, 16, ONE_NUM);
set_driver(mod_id, slot, 5, 16, ONE_NUM);
set_driver(mod_id, slot, 6, 16, ONE_NUM);
set_driver(mod_id, slot, 7, 16, ONE_NUM);
set_driver(mod_id, slot, 8, 16, ONE_NUM);
set_driver(mod_id, slot, 9, 16, ONE_NUM);
set_driver(mod_id, slot, 10, 16, ONE_NUM);
set_driver(mod_id, slot, 11, 16, ONE_NUM);
set_driver(mod_id, slot, 12, 16, ONE_NUM);
set_driver(mod_id, slot, 13, 16, ONE_NUM);
set_driver(mod_id, slot, 14, 16, ONE_NUM);
set_driver(mod_id, slot, 15, 16, ONE_NUM);
set_driver(mod_id, slot, 16, 16, ONE_NUM);
set_driver(mod_id, slot, 17, 16, ONE_NUM);
set_driver(mod_id, slot, 18, 16, ONE_NUM);
set_driver(mod_id, slot, 21, 16, ONE_NUM);
set_driver(mod_id, slot, 22, 16, ONE_NUM);
set_driver(mod_id, slot, 23, 16, ONE_NUM);
set_driver(mod_id, slot, 24, 16, ONE_NUM);
set_driver(mod_id, slot, 25, 16, ONE_NUM);
set_driver(mod_id, slot, 26, 16, ONE_NUM);
set_driver(mod_id, slot, 27, 16, ONE_NUM);
set_driver(mod_id, slot, 28, 16, ONE_NUM);
set_driver(mod_id, slot, 29, 16, ONE_NUM);
set_driver(mod_id, slot, 30, 16, ONE_NUM);
set_driver(mod_id, slot, 31, 16, ONE_NUM);
set_driver(mod_id, slot, 32, 16, ONE_NUM);
set_driver(mod_id, slot, 33, 16, ONE_NUM);
set_driver(mod_id, slot, 34, 16, ONE_NUM);
set_driver(mod_id, slot, 35, 16, ONE_NUM);
set_driver(mod_id, slot, 36, 16, ONE_NUM);
set_driver(mod_id, slot, 37, 16, ONE_NUM);
set_driver(mod_id, slot, 38, 16, ONE_NUM);
set_driver(mod_id, slot, 41, 16, ONE_NUM);
set_driver(mod_id, slot, 42, 16, ONE_NUM);
set_driver(mod_id, slot, 43, 16, ONE_NUM);
set_driver(mod_id, slot, 44, 16, ONE_NUM);
set_driver(mod_id, slot, 45, 16, ONE_NUM);
set_driver(mod_id, slot, 46, 16, ONE_NUM);
set_driver(mod_id, slot, 47, 16, ONE_NUM);
set_driver(mod_id, slot, 48, 16, ONE_NUM);
set_driver(mod_id, slot, 49, 16, ONE_NUM);
set_driver(mod_id, slot, 50, 16, ONE_NUM);
set_driver(mod_id, slot, 51, 16, ONE_NUM);
set_driver(mod_id, slot, 52, 16, ONE_NUM);
set_driver(mod_id, slot, 53, 16, ONE_NUM);
set_driver(mod_id, slot, 54, 16, ONE_NUM);
set_driver(mod_id, slot, 55, 16, ONE_NUM);
set_driver(mod_id, slot, 56, 16, ONE_NUM);
set_driver(mod_id, slot, 57, 16, ONE_NUM);
set_driver(mod_id, slot, 58, 16, ONE_NUM);
set_driver(mod_id, slot, 61, 16, ONE_NUM);
set_driver(mod_id, slot, 62, 16, ONE_NUM);
set_driver(mod_id, slot, 63, 16, ONE_NUM);
set_driver(mod_id, slot, 64, 16, ONE_NUM);
set_driver(mod_id, slot, 65, 16, ONE_NUM);
set_driver(mod_id, slot, 66, 16, ONE_NUM);
set_driver(mod_id, slot, 67, 16, ONE_NUM);
set_driver(mod_id, slot, 68, 16, ONE_NUM);
set_driver(mod_id, slot, 69, 16, ONE_NUM);
set_driver(mod_id, slot, 70, 16, ONE_NUM);
set_driver(mod_id, slot, 71, 16, ONE_NUM);
set_driver(mod_id, slot, 72, 16, ONE_NUM);
set_driver(mod_id, slot, 73, 16, ONE_NUM);
set_driver(mod_id, slot, 74, 16, ONE_NUM);
set_driver(mod_id, slot, 75, 16, ONE_NUM);
set_driver(mod_id, slot, 76, 16, ONE_NUM);
set_driver(mod_id, slot, 77, 16, ONE_NUM);
set_driver(mod_id, slot, 78, 16, ONE_NUM);
set_driver(mod_id, slot, 101, 16, ONE_NUM);
set_driver(mod_id, slot, 102, 16, ONE_NUM);
set_driver(mod_id, slot, 103, 16, ONE_NUM);
set_driver(mod_id, slot, 104, 16, ONE_NUM);
set_driver(mod_id, slot, 105, 16, ONE_NUM);
set_driver(mod_id, slot, 106, 16, ONE_NUM);
set_driver(mod_id, slot, 107, 16, ONE_NUM);
set_driver(mod_id, slot, 108, 16, ONE_NUM);
set_driver(mod_id, slot, 109, 16, ONE_NUM);
set_driver(mod_id, slot, 110, 16, ONE_NUM);
set_driver(mod_id, slot, 111, 16, ONE_NUM);
set_driver(mod_id, slot, 112, 16, ONE_NUM);
set_driver(mod_id, slot, 113, 16, ONE_NUM);
set_driver(mod_id, slot, 114, 16, ONE_NUM);
set_driver(mod_id, slot, 115, 16, ONE_NUM);
set_driver(mod_id, slot, 116, 16, ONE_NUM);
set_driver(mod_id, slot, 117, 16, ONE_NUM);
set_driver(mod_id, slot, 118, 16, ONE_NUM);
set_driver(mod_id, slot, 121, 16, ONE_NUM);
set_driver(mod_id, slot, 122, 16, ONE_NUM);
set_driver(mod_id, slot, 123, 16, ONE_NUM);
set_driver(mod_id, slot, 124, 16, ONE_NUM);
set_driver(mod_id, slot, 125, 16, ONE_NUM);
set_driver(mod_id, slot, 126, 16, ONE_NUM);
set_driver(mod_id, slot, 127, 16, ONE_NUM);
set_driver(mod_id, slot, 128, 16, ONE_NUM);
set_driver(mod_id, slot, 129, 16, ONE_NUM);
set_driver(mod_id, slot, 130, 16, ONE_NUM);
set_driver(mod_id, slot, 131, 16, ONE_NUM);
set_driver(mod_id, slot, 132, 16, ONE_NUM);
set_driver(mod_id, slot, 133, 16, ONE_NUM);
set_driver(mod_id, slot, 134, 16, ONE_NUM);
set_driver(mod_id, slot, 135, 16, ONE_NUM);
set_driver(mod_id, slot, 136, 16, ONE_NUM);
set_driver(mod_id, slot, 137, 16, ONE_NUM);
set_driver(mod_id, slot, 138, 16, ONE_NUM);
set_driver(mod_id, slot, 141, 16, ONE_NUM);
set_driver(mod_id, slot, 142, 16, ONE_NUM);
set_driver(mod_id, slot, 143, 16, ONE_NUM);
set_driver(mod_id, slot, 144, 16, ONE_NUM);
set_driver(mod_id, slot, 145, 16, ONE_NUM);
set_driver(mod_id, slot, 146, 16, ONE_NUM);
set_driver(mod_id, slot, 147, 16, ONE_NUM);
set_driver(mod_id, slot, 148, 16, ONE_NUM);
set_driver(mod_id, slot, 149, 16, ONE_NUM);
set_driver(mod_id, slot, 150, 16, ONE_NUM);
set_driver(mod_id, slot, 151, 16, ONE_NUM);
set_driver(mod_id, slot, 152, 16, ONE_NUM);
set_driver(mod_id, slot, 153, 16, ONE_NUM);
set_driver(mod_id, slot, 154, 16, ONE_NUM);
set_driver(mod_id, slot, 155, 16, ONE_NUM);
set_driver(mod_id, slot, 156, 16, ONE_NUM);
set_driver(mod_id, slot, 157, 16, ONE_NUM);
set_driver(mod_id, slot, 158, 16, ONE_NUM);
set_driver(mod_id, slot, 161, 16, ONE_NUM);
set_driver(mod_id, slot, 162, 16, ONE_NUM);
set_driver(mod_id, slot, 163, 16, ONE_NUM);
set_driver(mod_id, slot, 164, 16, ONE_NUM);
set_driver(mod_id, slot, 165, 16, ONE_NUM);
set_driver(mod_id, slot, 166, 16, ONE_NUM);
set_driver(mod_id, slot, 167, 16, ONE_NUM);
set_driver(mod_id, slot, 168, 16, ONE_NUM);
set_driver(mod_id, slot, 169, 16, ONE_NUM);
set_driver(mod_id, slot, 170, 16, ONE_NUM);
set_driver(mod_id, slot, 171, 16, ONE_NUM);
set_driver(mod_id, slot, 172, 16, ONE_NUM);
set_driver(mod_id, slot, 173, 16, ONE_NUM);
set_driver(mod_id, slot, 174, 16, ONE_NUM);
set_driver(mod_id, slot, 175, 16, ONE_NUM);
set_driver(mod_id, slot, 176, 16, ONE_NUM);
set_driver(mod_id, slot, 177, 16, ONE_NUM);
set_driver(mod_id, slot, 178, 16, ONE_NUM);
farm_tic(mod_id);
end_vector();
start_vector(17, 2, 0, 1);
set_driver(mod_id, slot, 1, 17, ZERO_NUM);
set_driver(mod_id, slot, 2, 17, ZERO_NUM);
set_driver(mod_id, slot, 3, 17, ZERO_NUM);
set_driver(mod_id, slot, 4, 17, ZERO_NUM);
set_driver(mod_id, slot, 5, 17, ZERO_NUM);
set_driver(mod_id, slot, 6, 17, ZERO_NUM);
set_driver(mod_id, slot, 7, 17, ZERO_NUM);
set_driver(mod_id, slot, 8, 17, ZERO_NUM);
set_driver(mod_id, slot, 9, 17, ZERO_NUM);
set_driver(mod_id, slot, 10, 17, ZERO_NUM);
set_driver(mod_id, slot, 11, 17, ZERO_NUM);
set_driver(mod_id, slot, 12, 17, ZERO_NUM);
set_driver(mod_id, slot, 13, 17, ZERO_NUM);
set_driver(mod_id, slot, 14, 17, ZERO_NUM);
set_driver(mod_id, slot, 15, 17, ZERO_NUM);
set_driver(mod_id, slot, 16, 17, ZERO_NUM);
set_driver(mod_id, slot, 17, 17, ZERO_NUM);
set_driver(mod_id, slot, 18, 17, ZERO_NUM);
set_driver(mod_id, slot, 21, 17, ZERO_NUM);
set_driver(mod_id, slot, 22, 17, ZERO_NUM);
set_driver(mod_id, slot, 23, 17, ZERO_NUM);
set_driver(mod_id, slot, 24, 17, ZERO_NUM);
set_driver(mod_id, slot, 25, 17, ZERO_NUM);
set_driver(mod_id, slot, 26, 17, ZERO_NUM);
set_driver(mod_id, slot, 27, 17, ZERO_NUM);
set_driver(mod_id, slot, 28, 17, ZERO_NUM);
set_driver(mod_id, slot, 29, 17, ZERO_NUM);
set_driver(mod_id, slot, 30, 17, ZERO_NUM);
set_driver(mod_id, slot, 31, 17, ZERO_NUM);
set_driver(mod_id, slot, 32, 17, ZERO_NUM);
set_driver(mod_id, slot, 33, 17, ZERO_NUM);
set_driver(mod_id, slot, 34, 17, ZERO_NUM);
set_driver(mod_id, slot, 35, 17, ZERO_NUM);
set_driver(mod_id, slot, 36, 17, ZERO_NUM);
set_driver(mod_id, slot, 37, 17, ZERO_NUM);
set_driver(mod_id, slot, 38, 17, ZERO_NUM);
set_driver(mod_id, slot, 41, 17, ZERO_NUM);
set_driver(mod_id, slot, 42, 17, ZERO_NUM);
set_driver(mod_id, slot, 43, 17, ZERO_NUM);
set_driver(mod_id, slot, 44, 17, ZERO_NUM);
set_driver(mod_id, slot, 45, 17, ZERO_NUM);
set_driver(mod_id, slot, 46, 17, ZERO_NUM);
set_driver(mod_id, slot, 47, 17, ZERO_NUM);
set_driver(mod_id, slot, 48, 17, ZERO_NUM);
set_driver(mod_id, slot, 49, 17, ZERO_NUM);
set_driver(mod_id, slot, 50, 17, ZERO_NUM);
set_driver(mod_id, slot, 51, 17, ZERO_NUM);
set_driver(mod_id, slot, 52, 17, ZERO_NUM);
set_driver(mod_id, slot, 53, 17, ZERO_NUM);
set_driver(mod_id, slot, 54, 17, ZERO_NUM);
set_driver(mod_id, slot, 55, 17, ZERO_NUM);
set_driver(mod_id, slot, 56, 17, ZERO_NUM);
set_driver(mod_id, slot, 57, 17, ZERO_NUM);
set_driver(mod_id, slot, 58, 17, ZERO_NUM);
set_driver(mod_id, slot, 61, 17, ZERO_NUM);
set_driver(mod_id, slot, 62, 17, ZERO_NUM);
set_driver(mod_id, slot, 63, 17, ZERO_NUM);
set_driver(mod_id, slot, 64, 17, ZERO_NUM);
set_driver(mod_id, slot, 65, 17, ZERO_NUM);
set_driver(mod_id, slot, 66, 17, ZERO_NUM);
set_driver(mod_id, slot, 67, 17, ZERO_NUM);
set_driver(mod_id, slot, 68, 17, ZERO_NUM);
set_driver(mod_id, slot, 69, 17, ZERO_NUM);
set_driver(mod_id, slot, 70, 17, ZERO_NUM);
set_driver(mod_id, slot, 71, 17, ZERO_NUM);
set_driver(mod_id, slot, 72, 17, ZERO_NUM);
set_driver(mod_id, slot, 73, 17, ZERO_NUM);
set_driver(mod_id, slot, 74, 17, ZERO_NUM);
set_driver(mod_id, slot, 75, 17, ZERO_NUM);
set_driver(mod_id, slot, 76, 17, ZERO_NUM);
set_driver(mod_id, slot, 77, 17, ZERO_NUM);
set_driver(mod_id, slot, 78, 17, ZERO_NUM);
set_driver(mod_id, slot, 101, 17, ZERO_NUM);
set_driver(mod_id, slot, 102, 17, ZERO_NUM);
set_driver(mod_id, slot, 103, 17, ZERO_NUM);
set_driver(mod_id, slot, 104, 17, ZERO_NUM);
set_driver(mod_id, slot, 105, 17, ZERO_NUM);
set_driver(mod_id, slot, 106, 17, ZERO_NUM);
set_driver(mod_id, slot, 107, 17, ZERO_NUM);
set_driver(mod_id, slot, 108, 17, ZERO_NUM);
set_driver(mod_id, slot, 109, 17, ZERO_NUM);
set_driver(mod_id, slot, 110, 17, ZERO_NUM);
set_driver(mod_id, slot, 111, 17, ZERO_NUM);
set_driver(mod_id, slot, 112, 17, ZERO_NUM);
set_driver(mod_id, slot, 113, 17, ZERO_NUM);
set_driver(mod_id, slot, 114, 17, ZERO_NUM);
set_driver(mod_id, slot, 115, 17, ZERO_NUM);
set_driver(mod_id, slot, 116, 17, ZERO_NUM);
set_driver(mod_id, slot, 117, 17, ZERO_NUM);
set_driver(mod_id, slot, 118, 17, ZERO_NUM);
set_driver(mod_id, slot, 121, 17, ZERO_NUM);
set_driver(mod_id, slot, 122, 17, ZERO_NUM);
set_driver(mod_id, slot, 123, 17, ZERO_NUM);
set_driver(mod_id, slot, 124, 17, ZERO_NUM);
set_driver(mod_id, slot, 125, 17, ZERO_NUM);
set_driver(mod_id, slot, 126, 17, ZERO_NUM);
set_driver(mod_id, slot, 127, 17, ZERO_NUM);
set_driver(mod_id, slot, 128, 17, ZERO_NUM);
set_driver(mod_id, slot, 129, 17, ZERO_NUM);
set_driver(mod_id, slot, 130, 17, ZERO_NUM);
set_driver(mod_id, slot, 131, 17, ZERO_NUM);
set_driver(mod_id, slot, 132, 17, ZERO_NUM);
set_driver(mod_id, slot, 133, 17, ZERO_NUM);
set_driver(mod_id, slot, 134, 17, ZERO_NUM);
set_driver(mod_id, slot, 135, 17, ZERO_NUM);
set_driver(mod_id, slot, 136, 17, ZERO_NUM);
set_driver(mod_id, slot, 137, 17, ZERO_NUM);
set_driver(mod_id, slot, 138, 17, ZERO_NUM);
set_driver(mod_id, slot, 141, 17, ZERO_NUM);
set_driver(mod_id, slot, 142, 17, ZERO_NUM);
set_driver(mod_id, slot, 143, 17, ZERO_NUM);
set_driver(mod_id, slot, 144, 17, ZERO_NUM);
set_driver(mod_id, slot, 145, 17, ZERO_NUM);
set_driver(mod_id, slot, 146, 17, ZERO_NUM);
set_driver(mod_id, slot, 147, 17, ZERO_NUM);
set_driver(mod_id, slot, 148, 17, ZERO_NUM);
set_driver(mod_id, slot, 149, 17, ZERO_NUM);
set_driver(mod_id, slot, 150, 17, ZERO_NUM);
set_driver(mod_id, slot, 151, 17, ZERO_NUM);
set_driver(mod_id, slot, 152, 17, ZERO_NUM);
set_driver(mod_id, slot, 153, 17, ZERO_NUM);
set_driver(mod_id, slot, 154, 17, ZERO_NUM);
set_driver(mod_id, slot, 155, 17, ZERO_NUM);
set_driver(mod_id, slot, 156, 17, ZERO_NUM);
set_driver(mod_id, slot, 157, 17, ZERO_NUM);
set_driver(mod_id, slot, 158, 17, ZERO_NUM);
set_driver(mod_id, slot, 161, 17, ZERO_NUM);
set_driver(mod_id, slot, 162, 17, ZERO_NUM);
set_driver(mod_id, slot, 163, 17, ZERO_NUM);
set_driver(mod_id, slot, 164, 17, ZERO_NUM);
set_driver(mod_id, slot, 165, 17, ZERO_NUM);
set_driver(mod_id, slot, 166, 17, ZERO_NUM);
set_driver(mod_id, slot, 167, 17, ZERO_NUM);
set_driver(mod_id, slot, 168, 17, ZERO_NUM);
set_driver(mod_id, slot, 169, 17, ZERO_NUM);
set_driver(mod_id, slot, 170, 17, ZERO_NUM);
set_driver(mod_id, slot, 171, 17, ZERO_NUM);
set_driver(mod_id, slot, 172, 17, ZERO_NUM);
set_driver(mod_id, slot, 173, 17, ZERO_NUM);
set_driver(mod_id, slot, 174, 17, ZERO_NUM);
set_driver(mod_id, slot, 175, 17, ZERO_NUM);
set_driver(mod_id, slot, 176, 17, ZERO_NUM);
set_driver(mod_id, slot, 177, 17, ZERO_NUM);
set_driver(mod_id, slot, 178, 17, ZERO_NUM);
end_vector();
vmcEndVectorSection();
add_seq_loc(0, 1, SEQ_NO_FLAG);
add_seq_loc(1, 1, SEQ_NO_FLAG);
add_seq_loc(2, 1, SEQ_NO_FLAG);
add_seq_loc(3, 1, SEQ_NO_FLAG);
add_seq_loc(4, 1, SEQ_NO_FLAG);
add_seq_loc(5, 1, SEQ_NO_FLAG);
add_seq_loc(6, 1, SEQ_NO_FLAG);
add_seq_loc(7, 1, SEQ_NO_FLAG);
add_seq_loc(8, 1, SEQ_NO_FLAG);
add_seq_loc(9, 1, SEQ_NO_FLAG);
add_seq_loc(10, 1, SEQ_NO_FLAG);
add_seq_loc(11, 1, SEQ_NO_FLAG);
add_seq_loc(12, 1, SEQ_NO_FLAG);
add_seq_loc(13, 1, SEQ_NO_FLAG);
add_seq_loc(14, 1, SEQ_NO_FLAG);
add_seq_loc(15, 1, SEQ_NO_FLAG);
add_seq_loc(16, 16, SEQ_NO_FLAG);
add_seq_loc(17, 17, SEQ_NO_FLAG);
add_vect_cmd(0, 0, PROG_VCEOFF_FLAG+PROG_NOP_FLAG);
add_vect_cmd(1, 0, PROG_VCEOFF_FLAG+PROG_NOP_FLAG);
add_vect_cmd(2, 0, PROG_VCEOFF_FLAG+PROG_NOP_FLAG);
add_jmp_cmd(3, 0, 16, PROG_VCEOFF_FLAG+PROG_NOP_FLAG);
add_vect_cmd(16, 16, PROG_FE_FLAG+PROG_VCEOFF_FLAG);
add_jmpq_cmd(17, 17, CPU_BAR_NUM, 16, PROG_FE_FLAG+PROG_VCEOFF_FLAG);
add_vect_cmd(18, 0, PROG_VCEOFF_FLAG);
add_sls_cmd(19, 0, 12, PROG_VCEOFF_FLAG+PROG_NOP_FLAG);
add_vect_cmd(20, 0, PROG_VCEOFF_FLAG+PROG_NOP_FLAG);
add_vect_cmd(21, 0, PROG_VCEOFF_FLAG+PROG_NOP_FLAG+PROG_HALT_FLAG);
add_sls_cmd(22, 0, 2, PROG_VCEOFF_FLAG+PROG_NOP_FLAG);
end_digital();
