init_digital();
set_fclks_per_vector_pair(4);
set_receiver_range(1.500000,1.500000);
afc_channel1(mod_id, PROBE_NUM);
set_achan_rcv(mod_id, 1, ONE_TRI_NUM, 2, 100, 4, 100);
aconnect_arcv0(mod_id, 1, RRESP_NUM);
aconnect_arcv1(mod_id, 1, WERR_NUM);
output_drv_and_rcv_enable();
start_vector(0, 2, 256, 256);
end_vector();
start_vector(1, 2, 0, 1);
end_vector();
start_vector(16, 2, 0, 1);
set_areceiver(mod_id, 1, ZERO_TRI_NUM);
end_vector();
vmcEndVectorSection();
add_seq_loc(0, 1, SEQ_NO_FLAG);
add_seq_loc(1, 1, SEQ_NO_FLAG);
add_seq_loc(2, 1, SEQ_NO_FLAG);
add_seq_loc(3, 1, SEQ_NO_FLAG);
add_seq_loc(4, 1, SEQ_NO_FLAG);
add_seq_loc(5, 1, SEQ_NO_FLAG);
add_seq_loc(6, 1, SEQ_NO_FLAG);
add_seq_loc(7, 1, SEQ_NO_FLAG);
add_seq_loc(8, 1, SEQ_NO_FLAG);
add_seq_loc(9, 1, SEQ_NO_FLAG);
add_seq_loc(10, 1, SEQ_NO_FLAG);
add_seq_loc(11, 1, SEQ_NO_FLAG);
add_seq_loc(12, 1, SEQ_NO_FLAG);
add_seq_loc(13, 1, SEQ_NO_FLAG);
add_seq_loc(14, 1, SEQ_NO_FLAG);
add_seq_loc(15, 1, SEQ_NO_FLAG);
add_seq_loc(16, 16, SEQ_NO_FLAG);
add_vect_cmd(0, 0, PROG_VCEOFF_FLAG+PROG_NOP_FLAG);
add_vect_cmd(1, 0, PROG_NOP_FLAG);
add_vect_cmd(2, 0, PROG_NOP_FLAG);
add_jmp_cmd(3, 0, 16, PROG_NOP_FLAG);
add_vect_cmd(16, 16, PROG_VCEON_FLAG);
add_sls_cmd(17, 0, 13, PROG_NOP_FLAG);
add_vect_cmd(18, 0, PROG_VCEOFF_FLAG+PROG_NOP_FLAG+PROG_HALT_FLAG);
add_vect_cmd(19, 0, PROG_NOP_FLAG);
add_vect_cmd(20, 0, PROG_NOP_FLAG);
end_digital();
